---
title: "Grain counts"
output: html_document
date: "2023-02-07"
---

# Pliman

https://tiagoolivoto.github.io/pliman_tut/00_about.html 

```{r setup, include=FALSE}
# devtools::install_github("TiagoOlivoto/pliman", build_vignettes = FALSE)
library(pliman)
```

## ejemplo del paquete

```{r}
img <-image_pliman("soybean_touch.jpg", plot = TRUE)
soy <- analyze_objects(img, marker = "id")
soy
```

```{r cars}
# list.files()
list_res <- analyze_objects(pattern = "corn", show_image = FALSE)
```


```{r}
grain <- image_import("images/granos.jpeg", plot = TRUE)

count <- analyze_objects(grain, marker = "id")
count
```

# FIELDimageR

https://www.opendronemap.org/fieldimager/

```{r}
# devtools::install_github("OpenDroneMap/FIELDimageR")
library(FIELDimageR)
library(raster)
```

https://drive.google.com/open?id=1Tyr4cEvEBoaWqaHw8UWPW-X1unzEMAfk

```{r}
# Uploading image
EX.P <- stack("images/EX_Pollen.jpeg")

# Reducing image resolution (fast analysis)
EX.P <- aggregate(EX.P, fact=4) 

plotRGB(EX.P, r = 1, g = 2, b = 3)

# Shapefile using the entire image (extent = T)
EX.P.shapeFile<-fieldPolygon(EX.P,extent = T)

# Using index "BIM" to remove background (above 19)
EX.P.R1<- fieldMask(mosaic = EX.P,index = "BIM", cropValue = 19, cropAbove = T)
plotRGB(EX.P.R1$newMosaic)

# Counting all pollens above 0.01 size (all sample)
EX.P.Total<-fieldCount(mosaic = EX.P.R1$mask, fieldShape = EX.P.shapeFile$fieldShape, minSize = 0.01) 

# Using index "BIM" to identify germinated pollen grain (removing values above 16)
EX.P.R2<- fieldMask(mosaic = EX.P, index = "BIM", cropValue = 16, cropAbove = T)
plotRGB(EX.P.R2$newMosaic)

# Counting all germinated pollen above 0.005 
EX.P.<-fieldCount(mosaic = EX.P.R2$mask, fieldShape = EX.P.shapeFile$fieldShape, minSize = 0.005)

```

